name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - feat/deployment

env:
  GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
  SERVICE_NAME: patient-service
  REGION: us-central1
  WORKING_DIRECTORY: ./backend  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Build and push Docker image
        run: |
          cd ${{ env.WORKING_DIRECTORY }}
          IMAGE_NAME=gcr.io/${{ env.GCP_PROJECT }}/${{ env.SERVICE_NAME }}
          gcloud builds submit --tag $IMAGE_NAME .

      - name: Deploy to Cloud Run
        run: |
          IMAGE_NAME=gcr.io/${{ env.GCP_PROJECT }}/${{ env.SERVICE_NAME }}
          gcloud run deploy ${{ env.SERVICE_NAME }} --image $IMAGE_NAME --region ${{ env.REGION }} --platform managed --allow-unauthenticated
